package com.atom.chat.settings;

import com.atom.chat.config.AtomChatConfig;
import com.atom.chat.theme.ThemeService;
import com.atom.chat.ui.UiLayout;
import com.atom.chat.ui.UiTokens;
import org.junit.jupiter.api.Test;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Guards the about-page hero: the two bundled assets — the light geometric
 * ground and the red wordmark — and the geometry that places them.
 *
 * <p>Why an asset test at all. The hero's appearance is a shipped binary — a
 * decoded PNG cannot be reviewed in a diff — so the properties that <em>are</em>
 * checkable are pinned here instead: both files sit on the resource path the
 * loader actually reads, all three platforms ship the same bytes, the ground is
 * the light low-saturation geometric backdrop the redesign asked for (and no
 * longer the old high-saturation fluid with its orange/violet/blue/cyan
 * families), the wordmark really is a horizontal red logotype with its ground
 * keyed out (RGBA, clear corners, a solid red glyph body), and the contained
 * placement never lets the art run past the hero card at either end of the
 * width range the panel can produce.
 *
 * <p>Why the pixel families and not a golden image: the art is regenerated by
 * hand from the reference composition, so an exact-pixel comparison would be red
 * on every legitimate re-art and would get deleted. The base tone, the
 * saturation ceiling, the keyed mark and the contain fit are the properties the
 * brief actually names, and they are what a wrong asset (the old fluid, a
 * stretched crop, an opaque logo) breaks.
 *
 * <p>Why the source contract too: the drawing call itself needs a Skija
 * surface, but the placement does not — the renderer routes both layers through
 * {@code SettingsSectionPage.heroGroundRect} / {@code heroWordmarkRect}, and
 * those pure functions are called here and pinned at every card width the panel
 * can produce. What is left to the source text is the weak part: which asset is
 * loaded, and that the ground really does go through the helper under test.
 */
class AboutHeroAssetTest {

    /** The light geometric hero ground, repo-root relative from the resources root. */
    private static final String ART = "assets/atomchat/about_hero.png";

    /** The red wordmark that replaced the old square {@code logo_mark}. */
    private static final String WORDMARK = "assets/atomchat/logo_wordmark.png";

    /** The three shipping targets, in the order the matrix lists them. */
    private static final List<String> PLATFORMS = List.of(
            "platforms/1.20.1-forge",
            "platforms/1.21.1-fabric",
            "platforms/1.21.1-neoforge");

    /**
     * The hero renderer, one copy per mapping family: Fabric keeps the Yarn
     * names, the official layer serves Forge and NeoForge. Both copies must
     * honour the same asset contract, or one platform ships a stale hero.
     */
    private static final List<String> HERO_SOURCES = List.of(
            "layers/mapping/official/src/main/java/com/atom/chat/settings/SettingsSectionPage.java",
            "platforms/1.21.1-fabric/src/main/java/com/atom/chat/settings/SettingsSectionPage.java");

    /**
     * The hero row's own height token. Only the card width varies with the
     * panel, so this token plus the art's decoded aspect is the whole placement
     * arithmetic.
     */
    private static final float HERO_H = UiTokens.SETTINGS_HERO_H;

    /**
     * Card widths the panel can actually hand the hero row: a small window's
     * clamped 242 up to the widest the 0.8 content zoom allows (704).
     */
    private static final float[] CARD_WIDTHS = {242.0F, 354.0F, 480.0F, 554.0F, 704.0F};

    /** The two ends of that range, named so a middle-only fit still fails. */
    private static final float NARROWEST_CARD = 242.0F;
    private static final float WIDEST_CARD = 704.0F;

    // ---------------------------------------------------------------- helpers

    private static Path repoRoot() {
        Path dir = Path.of("").toAbsolutePath();
        for (Path p = dir; p != null; p = p.getParent()) {
            if (Files.isDirectory(p.resolve("platforms"))) {
                return p;
            }
        }
        throw new AssertionError("repo root (the directory holding platforms/) not found above " + dir);
    }

    private static String source(String relative) throws IOException {
        return Files.readString(repoRoot().resolve(relative), StandardCharsets.UTF_8);
    }

    private static String sha256(Path file) throws IOException, NoSuchAlgorithmException {
        assertTrue(Files.isRegularFile(file), "missing asset: " + file);
        byte[] bytes = Files.readAllBytes(file);
        assertTrue(bytes.length > 0, "empty asset: " + file);
        byte[] digest = MessageDigest.getInstance("SHA-256").digest(bytes);
        StringBuilder hex = new StringBuilder(digest.length * 2);
        for (byte b : digest) {
            hex.append(Character.forDigit((b >> 4) & 0xF, 16)).append(Character.forDigit(b & 0xF, 16));
        }
        return hex.toString();
    }

    /** Decodes an asset from the runtime resource path — the same lookup
     *  {@code SettingsSectionPage.loadBundled} performs. */
    private static BufferedImage read(String resource) throws IOException {
        try (InputStream stream = AboutHeroAssetTest.class.getResourceAsStream("/" + resource)) {
            assertNotNull(stream, resource + " is not on the runtime resource path");
            BufferedImage image = ImageIO.read(stream);
            assertNotNull(image, resource + " is not a decodable image");
            return image;
        }
    }

    /** Rec. 709 luma of a packed ARGB pixel, 0..255. */
    private static float luma(int rgb) {
        int r = (rgb >> 16) & 0xFF;
        int g = (rgb >> 8) & 0xFF;
        int b = rgb & 0xFF;
        return 0.2126F * r + 0.7152F * g + 0.0722F * b;
    }

    /** The largest per-channel difference between two opaque ARGB colours. */
    private static int maxChannelDeviation(int a, int b) {
        return Math.max(Math.abs((a >> 16 & 0xFF) - (b >> 16 & 0xFF)),
                Math.max(Math.abs((a >> 8 & 0xFF) - (b >> 8 & 0xFF)),
                        Math.abs((a & 0xFF) - (b & 0xFF))));
    }

    /** HSV saturation (max-normalised), 0..1. */
    private static float saturation(int rgb) {
        int r = (rgb >> 16) & 0xFF;
        int g = (rgb >> 8) & 0xFF;
        int b = rgb & 0xFF;
        int max = Math.max(r, Math.max(g, b));
        int min = Math.min(r, Math.min(g, b));
        return max == 0 ? 0.0F : (max - min) / (float) max;
    }

    /** The hero card the renderer receives at one of the panel's widths. */
    private static UiLayout.Rect hero(float cardW) {
        return new UiLayout.Rect(12.0F, 34.0F, cardW, HERO_H);
    }

    /**
     * Checks a rect the <em>production</em> placement code returned — not a
     * restatement of its arithmetic — carries the art's own aspect, fits inside
     * the card, and is centred on both axes.
     *
     * <p>The contain/cover split lives in the {@code Math.min}: a cover branch
     * ({@code Math.max}) zooms one dimension past the card at every width the
     * panel can produce, so the overflow check is what tells the two apart.
     */
    private static void assertContained(UiLayout.Rect box, UiLayout.Rect card,
                                        float artW, float artH, String what) {
        String where = what + " in card " + card.w() + "x" + card.h() + " -> " + box;
        assertTrue(box.w() > 0.0F && box.h() > 0.0F, what + " has no area: " + where);
        assertEquals(artW / artH, box.w() / box.h(), 0.01F,
                what + " did not preserve its own aspect (a stretch?): " + where);
        assertTrue(box.w() <= card.w() + 0.01F && box.h() <= card.h() + 0.01F,
                what + " overflows the card — contain became a cover crop: " + where);
        assertTrue(box.x() >= card.x() - 0.01F && box.y() >= card.y() - 0.01F,
                what + " escapes the card origin: " + where);
        assertTrue(box.right() <= card.right() + 0.01F && box.bottom() <= card.bottom() + 0.01F,
                what + " escapes the card's far edge: " + where);
        assertEquals(card.x() + card.w() / 2.0F, box.x() + box.w() / 2.0F, 0.01F,
                what + " is not centred horizontally: " + where);
        assertEquals(card.y() + card.h() / 2.0F, box.y() + box.h() / 2.0F, 0.01F,
                what + " is not centred vertically: " + where);
    }

    // ------------------------------------------------------------ assertions

    /** All three platforms ship both files, and the copies are byte-identical. */
    @Test
    void allThreePlatformsShipTheSameTwoAssets() throws IOException, NoSuchAlgorithmException {
        for (String asset : List.of(ART, WORDMARK)) {
            Map<String, String> digests = new LinkedHashMap<>();
            for (String platform : PLATFORMS) {
                Path file = repoRoot().resolve(platform).resolve("src/main/resources").resolve(asset);
                digests.put(platform, sha256(file));
            }
            assertEquals(1, digests.values().stream().distinct().count(),
                    asset + " differs between platforms: " + digests);
        }
    }

    /** Both assets are where the code looks for them, and both are wide bands. */
    @Test
    void bothAssetsDecodeFromTheRuntimeResourcePath() throws IOException {
        BufferedImage art = read(ART);
        BufferedImage wordmark = read(WORDMARK);
        assertTrue(art.getWidth() > 0 && art.getHeight() > 0, "about_hero.png has no pixels");
        assertTrue(wordmark.getWidth() > 0 && wordmark.getHeight() > 0, "logo_wordmark.png has no pixels");
        // The hero row is HERO_H tall, so the ground is a wide strip, not a
        // near-square crop that would letterbox into a sliver.
        assertTrue(art.getWidth() > art.getHeight(),
                "about_hero.png is not a wide band (" + art.getWidth() + "x" + art.getHeight() + ")");
        assertTrue(wordmark.getWidth() > wordmark.getHeight(),
                "logo_wordmark.png is not horizontal (" + wordmark.getWidth() + "x" + wordmark.getHeight() + ")");
    }

    /**
     * The wordmark is a horizontal red logotype with its ground keyed out: RGBA
     * (an opaque RGB file would leave a white box), clear corners, a solid red
     * glyph body, a natural wide aspect, and mostly empty pixels — a keyed logo
     * rather than a full-frame block.
     */
    @Test
    void theWordmarkIsARedHorizontalRgbaMarkWithClearCorners() throws IOException {
        BufferedImage mark = read(WORDMARK);
        int w = mark.getWidth();
        int h = mark.getHeight();
        assertTrue(mark.getColorModel().hasAlpha(),
                "logo_wordmark.png has no alpha channel — its ground was not keyed out");
        float aspect = w / (float) h;
        assertTrue(aspect >= 1.8F && aspect <= 10.0F,
                "logo_wordmark.png aspect " + aspect + " is not a natural wordmark strip");

        for (int[] corner : new int[][]{{0, 0}, {w - 1, 0}, {0, h - 1}, {w - 1, h - 1}}) {
            assertEquals(0, mark.getRGB(corner[0], corner[1]) >>> 24,
                    "corner " + corner[0] + "," + corner[1]
                            + " is not transparent — the ground survived the key");
        }

        int opaque = 0;
        int red = 0;
        for (int y = 0; y < h; y++) {
            for (int x = 0; x < w; x++) {
                int argb = mark.getRGB(x, y);
                if ((argb >>> 24) < 200) {
                    continue;
                }
                opaque++;
                int r = (argb >> 16) & 0xFF;
                int g = (argb >> 8) & 0xFF;
                int b = argb & 0xFF;
                if (r > 140 && g < 100 && b < 100) {
                    red++;
                }
            }
        }
        assertTrue(red > 500, "the wordmark carries no red glyph body (" + red + " opaque red px)");
        assertTrue(opaque < (int) ((long) w * h * 3L / 4L),
                "the wordmark is a full-frame block (" + opaque + " opaque px), not a keyed logo");
    }

    /**
     * The ground is the light, low-saturation geometric backdrop — a light base
     * with pale shapes and negative space — and no longer the old fluid: that
     * art measured a mean luma of 126 with 99.5% of its pixels above 0.5
     * saturation and its four colour families (orange/violet/blue/cyan) each
     * over a fifth to a third of the frame. A fluid that drifted back, or a flat
     * fill with no shapes at all, fails the two ends of this test.
     */
    @Test
    void theHeroGroundIsLightGeometricNotTheOldFluid() throws IOException {
        BufferedImage art = read(ART);
        int pixels = 0;
        long lumaSum = 0;
        double lumaSq = 0.0;
        int light = 0;
        int dark = 0;
        int saturated = 0;
        for (int y = 0; y < art.getHeight(); y++) {
            for (int x = 0; x < art.getWidth(); x++) {
                int rgb = art.getRGB(x, y);
                float luma = luma(rgb);
                lumaSum += (long) luma;
                lumaSq += (double) luma * luma;
                pixels++;
                if (luma > 200.0F) {
                    light++;
                }
                if (luma < 60.0F) {
                    dark++;
                }
                if (saturation(rgb) > 0.5F) {
                    saturated++;
                }
            }
        }
        float mean = lumaSum / (float) pixels;
        float std = (float) Math.sqrt(Math.max(0.0, lumaSq / pixels - (double) mean * mean));
        float lightShare = light / (float) pixels;
        float darkShare = dark / (float) pixels;
        float saturatedShare = saturated / (float) pixels;

        assertTrue(mean > 170.0F,
                "the hero ground is not a light base (mean luma " + mean + " of 255)");
        assertTrue(lightShare > 0.40F,
                "the hero ground has almost no light negative space ("
                        + lightShare + " of pixels above luma 200)");
        assertTrue(darkShare < 0.05F,
                "the hero ground is dark (" + darkShare + " of pixels below luma 60)");
        assertTrue(saturatedShare < 0.20F,
                "the hero ground is the old high-saturation fluid (" + saturatedShare
                        + " of pixels above 0.5 saturation), not a light geometric ground");
        assertTrue(std > 3.0F,
                "the hero ground is a flat fill (luma std " + std + "), not geometric art");
    }

    /**
     * The fallback title reads on the ground. The hero card is filled with
     * {@code SETTINGS_HERO_GROUND} — near-white on every theme — so the ink must
     * come from that surface's own luminance ({@code UiTokens.onAccent}) rather
     * than from the panel's {@code textPrimary}: the pre-preset default is white
     * ({@code AtomChatConfig.textPrimaryColor = 0xFFFFFFFF}), which on this
     * ground is a contrast ratio of about 1.1:1 — invisible.
     *
     * <p>This is the whole missing-wordmark path, and it is also the path the
     * shipped asset takes wherever the PNG is not packaged.
     */
    @Test
    void theFallbackTitleInkReadsOnTheNearWhiteGround() throws IOException {
        int ink = UiTokens.onAccent(UiTokens.SETTINGS_HERO_GROUND);
        float ratio = contrast(ink, UiTokens.SETTINGS_HERO_GROUND);
        assertTrue(ratio >= 4.5F,
                "the fallback title on the hero ground is below WCAG AA (" + ratio + ":1, ink "
                        + Integer.toHexString(ink));

        // The ink above is derived from the token — but the surface the fallback
        // title is actually painted on is the ground ART, which is drawn over
        // that fill. Every other assertion here is either an ink-vs-token or an
        // art-only claim, so nothing ties the token to the surface the text sits
        // on. Tie them: the token claims to BE the art's own base tone (the
        // documented reason the letterbox seam is invisible), so its colour must
        // actually be the large flat region the art is painted on. Only then
        // does the ink-vs-token ratio above describe what the title is drawn on
        // — otherwise the card fill and the art are two different surfaces.
        BufferedImage art = read(ART);
        int token = UiTokens.SETTINGS_HERO_GROUND;
        long onBase = 0;
        for (int y = 0; y < art.getHeight(); y++) {
            for (int x = 0; x < art.getWidth(); x++) {
                if (maxChannelDeviation(art.getRGB(x, y), token) <= 4) {
                    onBase++;
                }
            }
        }
        float baseShare = onBase / (float) (art.getWidth() * art.getHeight());
        assertTrue(baseShare >= 0.25F,
                "SETTINGS_HERO_GROUND (" + Integer.toHexString(token) + ") is no longer the base"
                        + " tone the ground art is painted on (" + Math.round(baseShare * 100.0F)
                        + "% of the art within 4/255 per channel of it): the card fill and the art"
                        + " are two different surfaces now, so the ink picked from the token no"
                        + " longer describes the surface the title is drawn on");

        // The failure this rule exists for: the themes whose own primary is
        // near-white, the factory default among them, are unreadable on the
        // ground. If the shipped list ever loses that property, the polarity
        // choice is no longer forced — and this test says so instead of
        // silently asserting nothing.
        int nearWhitePrimaries = 0;
        for (ThemeService.Preset preset : ThemeService.presets()) {
            if (contrast(preset.textPrimary(), UiTokens.SETTINGS_HERO_GROUND) < 2.0F) {
                nearWhitePrimaries++;
            }
        }
        assertTrue(ThemeService.presets().length >= 8,
                "the preset list shrank; this loop no longer covers the shipped themes");
        assertTrue(contrast(AtomChatConfig.DEFAULT.textPrimaryColor, UiTokens.SETTINGS_HERO_GROUND) < 2.0F,
                "the factory-default primary is no longer unreadable on the near-white ground;"
                        + " the reason this polarity exists has changed");
        assertTrue(nearWhitePrimaries > 0,
                "no shipped preset has a near-white primary — the ground-vs-textPrimary hazard"
                        + " this test documents has gone away");
    }

    /** WCAG contrast ratio between two opaque ARGB colours, alpha ignored. */
    private static float contrast(int a, int b) {
        float la = relativeLuminance(a);
        float lb = relativeLuminance(b);
        float hi = Math.max(la, lb);
        float lo = Math.min(la, lb);
        return (hi + 0.05F) / (lo + 0.05F);
    }

    /** WCAG relative luminance — the same rule as {@code ThemeService}. */
    private static float relativeLuminance(int argb) {
        float r = srgbToLinear((argb >>> 16 & 0xFF) / 255.0F);
        float g = srgbToLinear((argb >>> 8 & 0xFF) / 255.0F);
        float b = srgbToLinear((argb & 0xFF) / 255.0F);
        return 0.2126F * r + 0.7152F * g + 0.0722F * b;
    }

    private static float srgbToLinear(float c) {
        return c <= 0.04045F ? c / 12.92F : (float) Math.pow((c + 0.055F) / 1.055F, 2.4);
    }

    /**
     * The ground's placement, asserted against the production function that
     * draws it ({@code SettingsSectionPage.heroGroundRect}) at both ends of the
     * width range the panel can produce. A cover crop (the same expression with
     * {@code Math.max}) overflows the row at every width, so the containment
     * claim is arithmetic here, not a helper name.
     */
    @Test
    void theHeroGroundIsContainedNotCoverCroppedAtEveryCardWidth() throws IOException {
        BufferedImage art = read(ART);
        float artW = art.getWidth();
        float artH = art.getHeight();
        for (float cardW : CARD_WIDTHS) {
            UiLayout.Rect card = hero(cardW);
            assertContained(SettingsSectionPage.heroGroundRect(card, artW, artH),
                    card, artW, artH, "the hero ground");
        }
        // Both ends named explicitly: a middle-only fit still fails.
        assertContained(SettingsSectionPage.heroGroundRect(hero(NARROWEST_CARD), artW, artH),
                hero(NARROWEST_CARD), artW, artH, "the hero ground at the narrowest card");
        assertContained(SettingsSectionPage.heroGroundRect(hero(WIDEST_CARD), artW, artH),
                hero(WIDEST_CARD), artW, artH, "the hero ground at the widest card");
    }

    /**
     * The wordmark box, likewise against the production function
     * ({@code SettingsSectionPage.heroWordmarkRect}): the mark's own aspect is
     * preserved, the box stays inside the {@code SETTINGS_HERO_PAD} inset on
     * every edge, and it never exceeds the {@code SETTINGS_HERO_WORDMARK_MAX_W}
     * by {@code _MAX_H} caps — a stretch to the whole card, a dropped pad or a
     * dropped cap each fail here.
     */
    @Test
    void theWordmarkBoxIsContainedPaddedAndCappedAtEveryCardWidth() throws IOException {
        BufferedImage mark = read(WORDMARK);
        float markW = mark.getWidth();
        float markH = mark.getHeight();
        for (float cardW : CARD_WIDTHS) {
            UiLayout.Rect card = hero(cardW);
            UiLayout.Rect box = SettingsSectionPage.heroWordmarkRect(card, markW, markH);
            assertContained(box, card, markW, markH, "the wordmark box");
            String where = "card " + cardW + " -> " + box;
            assertTrue(box.w() <= UiTokens.SETTINGS_HERO_WORDMARK_MAX_W + 0.01F,
                    "the wordmark box is wider than SETTINGS_HERO_WORDMARK_MAX_W: " + where);
            assertTrue(box.h() <= UiTokens.SETTINGS_HERO_WORDMARK_MAX_H + 0.01F,
                    "the wordmark box is taller than SETTINGS_HERO_WORDMARK_MAX_H: " + where);
            float pad = UiTokens.SETTINGS_HERO_PAD;
            assertTrue(box.x() >= card.x() + pad - 0.01F
                            && box.right() <= card.right() - pad + 0.01F
                            && box.y() >= card.y() + pad - 0.01F
                            && box.bottom() <= card.bottom() - pad + 0.01F,
                    "the wordmark box comes closer than SETTINGS_HERO_PAD to a card edge: " + where);
        }
    }

    /** A degenerate card or a degenerate decode is a skip, never a crash or a
     *  negative-size rect. */
    @Test
    void theTwoPlacementFunctionsDegradeToAZeroRect() {
        // A card with no width (and, for the padded wordmark box, one too narrow
        // to keep the pad on both sides) places nothing rather than a negative box.
        for (float cardW : new float[]{0.0F, UiTokens.SETTINGS_HERO_PAD}) {
            UiLayout.Rect box = SettingsSectionPage.heroWordmarkRect(
                    hero(cardW), 2346.0F, 409.0F);
            assertEquals(0.0F, box.w(), 0.01F, "a card with no room for the pad must place nothing: " + box);
            assertEquals(0.0F, box.h(), 0.01F, "a card with no room for the pad must place nothing: " + box);
        }
        UiLayout.Rect empty = SettingsSectionPage.heroGroundRect(hero(0.0F), 1200.0F, 360.0F);
        assertEquals(0.0F, empty.w(), 0.01F, "a zero-width card must place nothing: " + empty);
        assertEquals(0.0F, empty.h(), 0.01F, "a zero-width card must place nothing: " + empty);

        UiLayout.Rect card = hero(WIDEST_CARD);
        assertEquals(0.0F, SettingsSectionPage.heroGroundRect(card, 0.0F, 0.0F).w(), 0.01F,
                "a zero-extent decode must place nothing");
        assertEquals(0.0F, SettingsSectionPage.heroWordmarkRect(card, 0.0F, 0.0F).w(), 0.01F,
                "a zero-extent decode must place nothing");
    }

    /**
     * The renderer's own asset and placement decisions, asserted at the source:
     * it loads the light ground and the wordmark, the old square mark is gone,
     * and it draws both layers through their contain helpers
     * ({@link SettingsSectionPage#heroGroundRect} and
     * {@link SettingsSectionPage#heroWordmarkRect}) rather than a cover crop or
     * a stretch.
     *
     * <p>This is the weak half — a string landmark. The geometry itself is
     * asserted against {@code heroGroundRect}/{@code heroWordmarkRect} above,
     * but those tests call the helpers directly, so they cannot see a call site
     * that was replaced. This test is the only thing tying each helper to the
     * renderer: the helper must stay the only path from {@code drawHero} to a
     * {@code drawRoundedImage} for <em>both</em> the ground and the wordmark,
     * or the pinned geometry stops describing what ships.</p>
     */
    @Test
    void theHeroRendererLoadsTheWordmarkAndContainDrawsIt() throws IOException {
        for (String hero : HERO_SOURCES) {
            String src = source(hero);
            assertTrue(src.contains("about_hero.png"),
                    hero + ": the hero must load the bundled about_hero ground");
            assertTrue(src.contains("logo_wordmark.png"),
                    hero + ": the hero must load the wordmark (logo_wordmark.png),"
                            + " not the old square mark");
            assertFalse(src.contains("logo_mark.png"),
                    hero + ": the old square logo_mark asset is still referenced");
            assertFalse(src.contains("drawImageCover("),
                    hero + ": the hero must contain the art (letterbox), not cover-crop it —"
                            + " a cover crop zooms the light ground and cuts the negative space");
            assertTrue(src.contains("heroGroundRect(rect, art.getWidth(), art.getHeight())"),
                    hero + ": the ground must be placed by heroGroundRect, the function this"
                            + " suite pins the contain geometry of — an inline Math.max/min here"
                            + " would ship untested");
            assertTrue(src.contains("heroWordmarkRect(rect, mark.getWidth(), mark.getHeight())"),
                    hero + ": the wordmark must be placed by heroWordmarkRect, the function this"
                            + " suite pins the contain/pad/cap geometry of — a whole-card stretch"
                            + " here (new UiLayout.Rect(rect.x(), rect.y(), rect.w(), rect.h()))"
                            + " would ship untested, because the arithmetic tests call the helper"
                            + " directly and never see its call site");
            assertTrue(src.contains("UiTokens.onAccent(UiTokens.SETTINGS_HERO_GROUND)"),
                    hero + ": the missing-wordmark title must take its ink from the ground's own"
                            + " luminance; the panel's textPrimary is white on the near-white"
                            + " ground on the default and on most themes");
        }
    }
}
