package com.atom.chat.settings;

import com.atom.chat.ui.UiLayout;
import com.atom.chat.ui.UiTokens;
import org.junit.jupiter.api.Test;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Guards the about-page hero: the two bundled assets and the geometry that
 * places the emblem on them.
 *
 * <p>Why an asset test at all. The hero is the one surface in this mod whose
 * whole appearance is a shipped binary — a decoded PNG cannot be reviewed in a
 * diff — so the properties that <em>are</em> checkable are pinned here instead:
 * the art is on the resource path the loader actually reads, the three
 * platforms ship the same bytes, the art carries the four colour families the
 * redesign asked for, it reserves a cool band exactly where the red emblem
 * lands at every card width the panel can produce, and the mark really is the
 * logo with its white ground keyed out (clear corners, intact red body, the
 * soft shadow kept) rather than the opaque original under a new name.
 *
 * <p>Why the hue checks and not a golden image: the art is regenerated by hand
 * from the reference composition, so an exact-pixel comparison would be red on
 * every legitimate re-art and would get deleted. The families, the reserved
 * band and the keyed mark are the properties the brief actually names, and
 * they are what a wrong asset (a stretched crop, an opaque logo, a warm centre
 * that swallows the red) breaks.
 *
 * <p>Composition checks read the shader-free art only. The emblem is drawn over
 * it by the renderer, so nothing here asserts the red is in the fluid.
 */
class AboutHeroAssetTest {

    /** Repo-root relative, both from the resources root. */
    private static final String ART = "assets/atomchat/about_hero.png";
    private static final String MARK = "assets/atomchat/logo_mark.png";

    /** The three shipping targets, in the order the matrix lists them. */
    private static final List<String> PLATFORMS = List.of(
            "platforms/1.20.1-forge",
            "platforms/1.21.1-fabric",
            "platforms/1.21.1-neoforge");

    /** The shipped art's pixel size. The renderer only ever cover-crops it, so
     *  this is the only place the art's own aspect is asserted. */
    private static final int ART_W = 960;
    private static final int ART_H = 320;

    /**
     * Card widths the panel can actually hand the hero row: {@code s(480) /
     * contentScale} minus the list insets, from a small window's clamped 242 up
     * to the widest the 0.8 content zoom allows (704). The height never moves —
     * it is the HERO row's own token.
     */
    private static final float[] CARD_WIDTHS = {242.0F, 354.0F, 480.0F, 554.0F, 704.0F};

    private static final float HERO_H = UiTokens.SETTINGS_HERO_H;
    private static final float EMBLEM_SIDE = UiTokens.SETTINGS_HERO_PLATE;

    // ---------------------------------------------------------------- helpers

    private static Path repoRoot() {
        Path dir = Path.of("").toAbsolutePath();
        for (Path p = dir; p != null; p = p.getParent()) {
            if (Files.isDirectory(p.resolve("platforms"))) {
                return p;
            }
        }
        throw new AssertionError("repo root (the directory holding platforms/) not found above " + dir);
    }

    private static String sha256(Path file) throws IOException, NoSuchAlgorithmException {
        assertTrue(Files.isRegularFile(file), "missing asset: " + file);
        byte[] bytes = Files.readAllBytes(file);
        assertTrue(bytes.length > 0, "empty asset: " + file);
        byte[] digest = MessageDigest.getInstance("SHA-256").digest(bytes);
        StringBuilder hex = new StringBuilder(digest.length * 2);
        for (byte b : digest) {
            hex.append(Character.forDigit((b >> 4) & 0xF, 16)).append(Character.forDigit(b & 0xF, 16));
        }
        return hex.toString();
    }

    /** Decodes an asset from the runtime resource path — the same lookup
     *  {@code SettingsSectionPage.loadBundled} performs. */
    private static BufferedImage read(String resource) throws IOException {
        try (InputStream stream = AboutHeroAssetTest.class.getResourceAsStream("/" + resource)) {
            assertNotNull(stream, resource + " is not on the runtime resource path");
            BufferedImage image = ImageIO.read(stream);
            assertNotNull(image, resource + " is not a decodable image");
            return image;
        }
    }

    private static float hueDegrees(int rgb) {
        int r = (rgb >> 16) & 0xFF;
        int g = (rgb >> 8) & 0xFF;
        int b = rgb & 0xFF;
        int max = Math.max(r, Math.max(g, b));
        int min = Math.min(r, Math.min(g, b));
        int d = max - min;
        if (d == 0) {
            return -1.0F;
        }
        float hue;
        if (max == r) {
            hue = 60.0F * ((g - b) / (float) d);
        } else if (max == g) {
            hue = 60.0F * ((b - r) / (float) d) + 120.0F;
        } else {
            hue = 60.0F * ((r - g) / (float) d) + 240.0F;
        }
        return (hue % 360.0F + 360.0F) % 360.0F;
    }

    private static float saturation(int rgb) {
        int r = (rgb >> 16) & 0xFF;
        int g = (rgb >> 8) & 0xFF;
        int b = rgb & 0xFF;
        int max = Math.max(r, Math.max(g, b));
        int min = Math.min(r, Math.min(g, b));
        return max == 0 ? 0.0F : (max - min) / (float) max;
    }

    /** Fraction of a region that is saturated and inside the hue window. */
    private static float familyFraction(BufferedImage image, int x0, int y0, int x1, int y1,
                                        float fromHue, float toHue) {
        int total = 0;
        int hits = 0;
        for (int y = y0; y < y1; y++) {
            for (int x = x0; x < x1; x++) {
                int rgb = image.getRGB(x, y);
                total++;
                float hue = hueDegrees(rgb);
                if (hue >= fromHue && hue < toHue && saturation(rgb) > 0.25F) {
                    hits++;
                }
            }
        }
        assertTrue(total > 0, "empty region " + x0 + "," + y0 + " -> " + x1 + "," + y1);
        return hits / (float) total;
    }

    /**
     * The source window {@code SkiaDraw.drawImageCover} would take for a
     * destination of the given size: the largest centred window with the
     * destination's aspect. Restated here because that method cannot run
     * without a Skija surface, and the claim under test is "the emblem lands on
     * the art's calm centre at every card width" — which is this arithmetic.
     *
     * @return {x, y, width, height} in art pixels
     */
    private static float[] coverWindow(float cardW, float cardH) {
        float srcW;
        float srcH;
        if (ART_W * cardH > ART_H * cardW) {
            srcH = ART_H;
            srcW = srcH * cardW / cardH;
        } else {
            srcW = ART_W;
            srcH = srcW * cardH / cardW;
        }
        return new float[]{(ART_W - srcW) / 2.0F, (ART_H - srcH) / 2.0F, srcW, srcH};
    }

    // ------------------------------------------------------------ assertions

    /** All three platforms ship both files, and the copies are byte-identical. */
    @Test
    void allThreePlatformsShipTheSameTwoAssets() throws IOException, NoSuchAlgorithmException {
        for (String asset : List.of(ART, MARK)) {
            Map<String, String> digests = new LinkedHashMap<>();
            for (String platform : PLATFORMS) {
                Path file = repoRoot().resolve(platform).resolve("src/main/resources").resolve(asset);
                digests.put(platform, sha256(file));
            }
            assertEquals(1, digests.values().stream().distinct().count(),
                    asset + " differs between platforms: " + digests);
        }
    }

    /** The art is where the code looks for it, at the size the math assumes. */
    @Test
    void theArtIsOnTheRuntimeResourcePath() throws IOException {
        BufferedImage art = read(ART);
        assertEquals(ART_W, art.getWidth(), "about_hero.png width");
        assertEquals(ART_H, art.getHeight(), "about_hero.png height");
        // A wide strip: the hero row is 110 tall, so anything near square would
        // be cropped into a sliver by the cover crop.
        assertEquals(3.0F, ART_W / (float) ART_H, 0.01F, "the art's own aspect");
    }

    /**
     * The four families the redesign asked for are all actually in the picture,
     * each over a fifth-to-a-third of it. A fluid that drifted to one hue, or a
     * flat fill, fails here; the thresholds sit well under the shipped shares
     * (orange 17%, violet 33%, blue 12%, cyan 21%) so re-arting has room.
     */
    @Test
    void theArtCarriesOrangePurpleBlueAndCyan() throws IOException {
        BufferedImage art = read(ART);
        float orange = familyFraction(art, 0, 0, ART_W, ART_H, 15.0F, 70.0F);
        float violet = familyFraction(art, 0, 0, ART_W, ART_H, 250.0F, 330.0F);
        float blue = familyFraction(art, 0, 0, ART_W, ART_H, 220.0F, 250.0F);
        float cyan = familyFraction(art, 0, 0, ART_W, ART_H, 170.0F, 220.0F);
        assertTrue(orange > 0.10F, "warm orange share is only " + orange);
        assertTrue(violet > 0.20F, "purple/violet share is only " + violet);
        assertTrue(blue > 0.06F, "blue share is only " + blue);
        assertTrue(cyan > 0.12F, "cyan share is only " + cyan);
    }

    /**
     * The red mark needs a cool, low-contrast ground or it disappears into the
     * warm ribbons. This walks every card width the panel can produce, projects
     * the emblem's square through the same cover crop the renderer uses, and
     * requires that square to be cool-hued over most of its area (the shipped
     * art measures 0.87-1.00) with blue as its dominant channel.
     */
    @Test
    void theArtReservesACoolBandUnderTheEmblem() throws IOException {
        BufferedImage art = read(ART);
        for (float cardW : CARD_WIDTHS) {
            float[] window = coverWindow(cardW, HERO_H);
            float scale = window[3] / HERO_H;
            int x0 = Math.round(window[0] + (cardW - EMBLEM_SIDE) / 2.0F * scale);
            int x1 = Math.round(window[0] + (cardW + EMBLEM_SIDE) / 2.0F * scale);
            int y0 = Math.round(window[1] + (HERO_H - EMBLEM_SIDE) / 2.0F * scale);
            int y1 = Math.round(window[1] + (HERO_H + EMBLEM_SIDE) / 2.0F * scale);
            String where = "card " + cardW + "x" + HERO_H + " -> art rows " + y0 + ".." + y1
                    + " cols " + x0 + ".." + x1;
            assertTrue(x0 >= 0 && y0 >= 0 && x1 <= ART_W && y1 <= ART_H, "emblem patch escapes the art: " + where);

            float cool = 0.0F;
            long red = 0;
            long blue = 0;
            for (int y = y0; y < y1; y++) {
                for (int x = x0; x < x1; x++) {
                    int rgb = art.getRGB(x, y);
                    float hue = hueDegrees(rgb);
                    if (hue >= 170.0F && hue < 280.0F && saturation(rgb) > 0.2F) {
                        cool++;
                    }
                    red += (rgb >> 16) & 0xFF;
                    blue += rgb & 0xFF;
                }
            }
            int pixels = (x1 - x0) * (y1 - y0);
            cool /= pixels;
            assertTrue(cool > 0.75F, "the emblem's ground is not cool enough (" + cool + "): " + where);
            assertTrue(blue > red, "the emblem's ground is warm (r=" + red + ", b=" + blue + "): " + where);
        }
    }

    /**
     * The mark is the logo with its white ground keyed out and nothing else
     * changed: the four corners are fully transparent (an opaque original
     * renamed would leave them white), the red body survives as a solid,
     * fully-opaque, saturated mass, and the soft shadow survives as the
     * translucent neutral ring around it.
     */
    @Test
    void theMarkIsTheLogoWithItsWhiteGroundKeyedOut() throws IOException {
        BufferedImage mark = read(MARK);
        assertEquals(256, mark.getWidth(), "logo_mark.png width");
        assertEquals(256, mark.getHeight(), "logo_mark.png height");

        for (int[] corner : new int[][]{{0, 0}, {255, 0}, {0, 255}, {255, 255}}) {
            int argb = mark.getRGB(corner[0], corner[1]);
            assertEquals(0, argb >>> 24, "corner " + corner[0] + "," + corner[1]
                    + " is not transparent — the white ground survived the key");
        }

        int opaqueRed = 0;
        int translucentNeutral = 0;
        int opaque = 0;
        for (int y = 0; y < mark.getHeight(); y++) {
            for (int x = 0; x < mark.getWidth(); x++) {
                int argb = mark.getRGB(x, y);
                int alpha = argb >>> 24;
                int r = (argb >> 16) & 0xFF;
                int g = (argb >> 8) & 0xFF;
                int b = argb & 0xFF;
                if (alpha >= 250) {
                    opaque++;
                    if (r > 150 && g < 90 && b < 90) {
                        opaqueRed++;
                    }
                } else if (alpha > 10 && alpha < 200) {
                    int max = Math.max(r, Math.max(g, b));
                    int min = Math.min(r, Math.min(g, b));
                    if (max - min < 12) {
                        translucentNeutral++;
                    }
                }
            }
        }
        assertTrue(opaqueRed > 4000, "the red body did not survive the key (" + opaqueRed + " opaque red px)");
        assertEquals(opaque, opaqueRed,
                "the opaque body is not uniformly red — the key left a coloured fringe");
        assertTrue(translucentNeutral > 500,
                "the soft drop shadow is gone (" + translucentNeutral + " translucent neutral px)");
        // And the key really did shrink the asset: a full 256x256 opaque logo
        // would be 65536 opaque pixels.
        assertTrue(opaque < 40000, "the mark is still a full-frame opaque image (" + opaque + " opaque px)");
    }

    /**
     * The emblem is centred on the hero card on both axes and sized off the
     * hero's own emblem token, so it scales with the row rather than with the
     * panel width — and it always fits inside the row.
     */
    @Test
    void theEmblemIsCentredAndSizedOffTheEmblemToken() {
        for (float cardW : CARD_WIDTHS) {
            UiLayout.Rect hero = new UiLayout.Rect(12.0F, 34.0F, cardW, HERO_H);
            UiLayout.Rect logo = SettingsSectionPage.heroLogoRect(hero);
            assertEquals(EMBLEM_SIDE, logo.w(), 0.001F, "emblem side must be SETTINGS_HERO_PLATE");
            assertEquals(logo.w(), logo.h(), 0.001F, "the emblem is square");
            assertEquals(hero.x() + hero.w() / 2.0F, logo.x() + logo.w() / 2.0F, 0.001F,
                    "emblem is not centred horizontally for card " + cardW);
            assertEquals(hero.y() + hero.h() / 2.0F, logo.y() + logo.h() / 2.0F, 0.001F,
                    "emblem is not centred vertically for card " + cardW);
            assertTrue(logo.x() >= hero.x() && logo.y() >= hero.y()
                            && logo.x() + logo.w() <= hero.x() + hero.w()
                            && logo.y() + logo.h() <= hero.y() + hero.h(),
                    "emblem escapes the hero card for card " + cardW);
        }
    }
}
